/**
 * MENU FIXTURE - demo content taken from the approved design handoff.
 *
 * Generated from prototype/storefront-data.js so the Arabic copy is exact
 * rather than retyped. No network, no credential, no production record. The
 * whole module disappears when a live adapter lands.
 */
import type { Category, HomeModules, MenuItem } from './types';

export const CATEGORIES: readonly Category[] = [
  {
    id: "burgers",
    name: "برجر لحم",
    image: "/tenant-maps-burger-item-burger.webp",
    iconPath: "M4 10h16a8 8 0 00-16 0zM3 14h18M4 17h16v1a2 2 0 01-2 2H6a2 2 0 01-2-2z",
    blurb: "لحم بقري طازج يُحضّر عند الطلب، مع خبز يُخبز يومياً.",
  },
  {
    id: "chicken",
    name: "برجر دجاج",
    image: null,
    iconPath: "M14 4.5a5.5 5.5 0 11-3.9 9.4L7 17l-1 3 3-1 3.1-3.1A5.5 5.5 0 0014 4.5z",
    blurb: null,
  },
  {
    id: "sides",
    name: "مقبلات وبطاطا",
    image: "/tenant-maps-burger-item-fries.webp",
    iconPath: "M7 10l-1 11h12l-1-11M7 10V5l2 1.5L12 4l3 2.5L17 5v5M7 10h10M10 14v4M14 14v4",
    blurb: null,
  },
  {
    id: "drinks",
    name: "مشروبات",
    image: null,
    iconPath: "M6 5h12l-1.3 15H7.3zM6.6 10h10.8M14 5l2.5-3",
    blurb: null,
  },
  {
    id: "desserts",
    name: "حلويات",
    image: "/tenant-maps-burger-item-sweet.webp",
    iconPath: "M5 12h14l-1 8H6zM5 12a7 7 0 0114 0M9 20v-4M12 20v-5M15 20v-4",
    blurb: null,
  },
  {
    id: "deals",
    name: "عروض ووجبات عائلية",
    image: "/tenant-maps-burger-item-plate.webp",
    iconPath: "M20.6 13.4l-7.2 7.2a2 2 0 01-2.8 0L3 13V4h9l8.6 8.6a.6.6 0 010 .8zM7.5 8.5h.01",
    blurb: "وجبات كاملة بسعر واحد — للفرد أو للعائلة.",
  },
  {
    id: "kids",
    name: "وجبات أطفال",
    image: null,
    iconPath: "M12 3a6 6 0 016 6c0 3.3-2.7 6-6 6s-6-2.7-6-6a6 6 0 016-6zM12 15v4M9 21h6M10 8.5h.01M14 8.5h.01",
    blurb: null,
  },
];

export const MENU_ITEMS: readonly MenuItem[] = [
  {
    id: "1",
    categoryId: "burgers",
    name: "Maps كلاسيك",
    description: "برجر لحم بقري 180 جم، جبنة شيدر، خس، طماطم، بصل مخلل، صوص خاص",
    priceMinor: 5500,
    image: "/tenant-maps-burger-item-burger.webp",
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["bun", "extras", "remove"],
  },
  {
    id: "2",
    categoryId: "burgers",
    name: "دابل سموكي",
    description: "شرائح لحم مزدوجة، جبنة مدخنة، بصل كراميل، صوص باربكيو حار",
    priceMinor: 7500,
    image: "/tenant-maps-burger-item-burger.webp",
    featured: true,
    signature: true,
    badge: "new",
    soldOut: false,
    hasOptions: true,
    groupIds: ["bun", "extras", "remove"],
  },
  {
    id: "4",
    categoryId: "burgers",
    name: "سبايسي ماشروم",
    description: "لحم بقري، فطر مشوي، جبنة بري، فلفل حار مشوي، مايونيز ثوم",
    priceMinor: 6500,
    image: null,
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["bun", "extras", "remove"],
  },
  {
    id: "5",
    categoryId: "burgers",
    name: "بلاك أنجوس",
    description: "لحم أنجوس 220 جم، جبنة بلو تشيز، طماطم مجففة، روكا، صوص ترفل",
    priceMinor: 9000,
    image: "/tenant-maps-burger-item-burger.webp",
    featured: false,
    signature: false,
    badge: null,
    soldOut: true,
    hasOptions: true,
    groupIds: ["bun", "extras", "remove"],
  },
  {
    id: "6",
    categoryId: "burgers",
    name: "فيجي برجر",
    description: "باتي نباتي من الفطر والعدس، خضار مشكل، صوص أفوكادو",
    priceMinor: 4800,
    image: null,
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["bun", "extras", "remove"],
  },
  {
    id: "3",
    categoryId: "chicken",
    name: "كريسبي تشيكن",
    description: "دجاج مقرمش مقلي، كول سلو، مخلل، صوص هاني ماسترد",
    priceMinor: 5000,
    image: "/tenant-maps-burger-item-burger.webp",
    featured: true,
    signature: true,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["bun", "extras", "remove"],
  },
  {
    id: "19",
    categoryId: "chicken",
    name: "تشيكن حار",
    description: "صدر دجاج متبل حار، خس، صوص رانش",
    priceMinor: 5200,
    image: null,
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["bun", "extras", "remove"],
  },
  {
    id: "7",
    categoryId: "sides",
    name: "بطاطا مقلية مقرمشة",
    description: "بطاطا طازجة مقلية بزيت نقي، مع صوص للاختيار",
    priceMinor: 2200,
    image: "/tenant-maps-burger-item-fries.webp",
    featured: true,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["sauce"],
  },
  {
    id: "8",
    categoryId: "sides",
    name: "أونيون رينج",
    description: "حلقات بصل مقرمشة بعجينة البيرة، صوص رانش خاص",
    priceMinor: 2800,
    image: null,
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["sauce"],
  },
  {
    id: "9",
    categoryId: "sides",
    name: "موزاريلا ستيكس",
    description: "6 قطع جبنة موزاريلا مقرمشة، صوص مارينارا حار",
    priceMinor: 3500,
    image: null,
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: false,
    groupIds: [],
  },
  {
    id: "11",
    categoryId: "sides",
    name: "ناجيتس دجاج",
    description: "8 قطع ناجيتس دجاج مقرمشة مع صوص للاختيار",
    priceMinor: 3200,
    image: "/tenant-maps-burger-item-fries.webp",
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["sauce"],
  },
  {
    id: "12",
    categoryId: "drinks",
    name: "شيك شوكولاتة",
    description: "شيك كريمي بالشوكولاتة الداكنة، كريمة مخفوقة",
    priceMinor: 3000,
    image: "/tenant-maps-burger-item-drink.webp",
    featured: true,
    signature: true,
    badge: "new",
    soldOut: false,
    hasOptions: false,
    groupIds: [],
  },
  {
    id: "13",
    categoryId: "drinks",
    name: "ليموناضة نعناع",
    description: "عصير ليمون طازج بالنعناع والثلج",
    priceMinor: 2200,
    image: null,
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: false,
    groupIds: [],
  },
  {
    id: "14",
    categoryId: "drinks",
    name: "كولا / سبرايت",
    description: "مشروب غازي مثلج، علبة 330 مل",
    priceMinor: 1200,
    image: null,
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: false,
    groupIds: [],
  },
  {
    id: "15",
    categoryId: "drinks",
    name: "كابتشينو",
    description: "قهوة بالحليب المبخر مع رش الكاكاو",
    priceMinor: 2800,
    image: "/tenant-maps-burger-item-drink.webp",
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: false,
    groupIds: [],
  },
  {
    id: "20",
    categoryId: "desserts",
    name: "براونيز شوكولاتة",
    description: "براونيز دافئ مع صوص شوكولاتة",
    priceMinor: 2400,
    image: "/tenant-maps-burger-item-sweet.webp",
    featured: true,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: false,
    groupIds: [],
  },
  {
    id: "21",
    categoryId: "desserts",
    name: "تشيز كيك لوتس",
    description: "تشيز كيك كريمي بطبقة لوتس",
    priceMinor: 2800,
    image: "/tenant-maps-burger-item-sweet.webp",
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: false,
    groupIds: [],
  },
  {
    id: "16",
    categoryId: "deals",
    name: "ميل كلاسيك",
    description: "Maps كلاسيك + بطاطا مقلية + مشروب غازي",
    priceMinor: 6900,
    image: "/tenant-maps-burger-item-plate.webp",
    featured: false,
    signature: true,
    badge: "deal",
    soldOut: false,
    hasOptions: true,
    groupIds: ["bun", "meal"],
  },
  {
    id: "17",
    categoryId: "deals",
    name: "فاميلي باكج",
    description: "4 برجر + 2 بطاطا كبيرة + 4 مشروبات، مثالي للعائلة",
    priceMinor: 24900,
    image: "/tenant-maps-burger-item-plate.webp",
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["meal"],
  },
  {
    id: "22",
    categoryId: "kids",
    name: "ميني برجر أطفال",
    description: "برجر صغير مع بطاطا وعصير",
    priceMinor: 3500,
    image: null,
    featured: false,
    signature: false,
    badge: null,
    soldOut: false,
    hasOptions: true,
    groupIds: ["meal"],
  },
];

export const HOME_MODULES: HomeModules = {
  announcement: { text: "يوم الجمعة: توصيل مجاني داخل كفر مندا على كل طلب فوق ₪80" },
  campaign: { title: "كل لقمة… مغامرة", subline: "برجر يُشوى عند الطلب" },
  promo: {
    kicker: "COMBO",
    title: "ميل كلاسيك",
    body: "Maps كلاسيك + بطاطا مقلية + مشروب غازي",
    image: "/tenant-maps-burger-item-plate.webp",
    priceMinor: 6900,
    itemId: "16",
  },
  story: {
    kicker: "قصتنا",
    title: "لحم طازج، وخبز يُخبز عندنا",
    body: "بدأنا بعربة صغيرة في كفر مندا، واليوم نطحن اللحم كل صباح ونخبز الخبز في مطبخنا. كل برجر يُحضّر عند الطلب — لا شيء جاهز مسبقاً.",
    image: "/tenant-maps-burger-story.webp",
    facts: ["لحم بقري طازج يومياً", "خبز من مطبخنا", "زيت المقلاة يُغيَّر مرتين يومياً"],
  },
  popular: { enabled: true, ready: true },
};

/** Configured VAT rate. Configuration, not a legal decision by any component. */
/**
 * Identifies THIS menu's id-space. A persisted cart stores item, group and
 * option IDS, so it is only meaningful against the menu those ids came from -
 * bump this whenever an id is reused for different content, and every stored
 * cart for the old menu is discarded instead of resolving to the wrong thing.
 */
export const MENU_VERSION = 'mb-1';

export const TAX_RATE = 0.18;
