-- STOREFRONT-SEC-001 RECOVERY — restores ONLY the anon privileges proven present on hosted BEFORE apply.
-- Source: read-only hosted inventory of project oqmevrndtivqxgyvcmwy (RestoFlow, eu-west-1), migrations 139/139 head 20260905090001.
-- Do NOT run unless the SEC-001 apply caused a verified regression and the owner has approved recovery.
begin;
-- 1. Function EXECUTE grants that existed for anon (explicit anon=X/postgres entries): 78 functions
grant execute on function public.activate_device(p_client_request_id uuid, p_device_pairing_id uuid) to anon;
grant execute on function public.approve_device(p_client_request_id uuid, p_device_pairing_id uuid) to anon;
grant execute on function public.create_device(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_device_type text, p_label text) to anon;
grant execute on function public.create_organization(p_client_request_id uuid, p_organization_name text, p_organization_slug text, p_restaurant_name text, p_branch_name text, p_currency_code text, p_timezone text, p_default_station_name text) to anon;
grant execute on function public.create_staff_member(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_display_name text, p_role text, p_capabilities jsonb) to anon;
grant execute on function public.delete_floor_element(p_client_request_id uuid, p_organization_id uuid, p_element_id uuid) to anon;
grant execute on function public.get_branch_kitchen_workflow_mode(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid) to anon;
grant execute on function public.get_branch_pos_shift_close_enabled(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid) to anon;
grant execute on function public.get_branch_tax(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid) to anon;
grant execute on function public.get_device_branch_tax(p_device_id uuid, p_session_token text) to anon;
grant execute on function public.get_device_pos_shift_close_enabled(p_device_id uuid, p_session_token text) to anon;
grant execute on function public.get_device_printer_assignments(p_device_id uuid, p_session_token text) to anon;
grant execute on function public.get_my_context() to anon;
grant execute on function public.get_restaurant_receipt_logo(p_organization_id uuid, p_restaurant_id uuid) to anon;
grant execute on function public.grant_membership(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_target_app_user_id uuid, p_role text) to anon;
grant execute on function public.issue_device_enrollment_code(p_client_request_id uuid, p_device_id uuid, p_ttl interval) to anon;
grant execute on function public.kiosk_menu(p_device_id uuid, p_session_token text) to anon;
grant execute on function public.kiosk_submit_order(p_device_id uuid, p_session_token text, p_order_id uuid, p_local_operation_id text, p_order_type text, p_table_id uuid, p_currency_code text, p_notes text, p_customer_name text, p_customer_phone text, p_order_items jsonb, p_client_subtotal_minor bigint, p_client_discount_total_minor bigint, p_client_tax_total_minor bigint, p_client_grand_total_minor bigint, p_client_created_at timestamp with time zone, p_claim_kitchen_dispatch boolean) to anon;
grant execute on function public.kiosk_tables(p_device_id uuid, p_session_token text) to anon;
grant execute on function public.list_device_staff(p_device_id uuid, p_session_token text) to anon;
grant execute on function public.list_devices(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid) to anon;
grant execute on function public.list_members(p_organization_id uuid) to anon;
grant execute on function public.list_menu(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid) to anon;
grant execute on function public.list_org_structure(p_organization_id uuid) to anon;
grant execute on function public.list_printers(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid) to anon;
grant execute on function public.list_quick_note_presets(p_organization_id uuid, p_restaurant_id uuid) to anon;
grant execute on function public.list_staff(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid) to anon;
grant execute on function public.list_tables(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid) to anon;
grant execute on function public.menu_reorder(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_entity text, p_ids uuid[]) to anon;
grant execute on function public.menu_soft_delete(p_organization_id uuid, p_entity text, p_id uuid) to anon;
grant execute on function public.menu_upsert_category(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid, p_name text, p_display_order integer, p_is_active boolean, p_icon_key text) to anon;
grant execute on function public.menu_upsert_item(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid, p_menu_category_id uuid, p_name text, p_description text, p_base_price_minor bigint, p_currency_code text, p_default_station_id uuid, p_display_order integer, p_is_active boolean, p_image_path text, p_item_type text, p_tags jsonb, p_prep_minutes integer, p_sku text, p_kitchen_note text, p_attributes jsonb) to anon;
grant execute on function public.menu_upsert_modifier(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid, p_menu_item_id uuid, p_name text, p_selection_type text, p_min_select integer, p_max_select integer, p_is_required boolean, p_display_order integer, p_is_active boolean, p_allow_quantity boolean, p_max_quantity integer) to anon;
grant execute on function public.menu_upsert_modifier_option(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid, p_modifier_id uuid, p_name text, p_price_delta_minor bigint, p_display_order integer, p_is_active boolean, p_kitchen_meat jsonb) to anon;
grant execute on function public.menu_upsert_size(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid, p_menu_item_id uuid, p_name text, p_price_delta_minor bigint, p_display_order integer, p_is_active boolean) to anon;
grant execute on function public.menu_upsert_variant(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid, p_menu_item_id uuid, p_name text, p_price_delta_minor bigint, p_display_order integer, p_is_active boolean) to anon;
grant execute on function public.owner_order_detail(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_order_id uuid) to anon;
grant execute on function public.platform_admin_get_organization(p_organization_id uuid, p_reason text) to anon;
grant execute on function public.platform_admin_organization_overview(p_reason text) to anon;
grant execute on function public.platform_admin_recent_audit(p_reason text, p_limit integer) to anon;
grant execute on function public.pos_menu(p_pin_session_id uuid, p_device_id uuid) to anon;
grant execute on function public.pos_tables(p_pin_session_id uuid, p_device_id uuid) to anon;
grant execute on function public.redeem_device_enrollment_code(p_client_request_id uuid, p_device_id uuid, p_enrollment_code text) to anon;
grant execute on function public.redeem_device_pairing(p_enrollment_code text, p_device_type text) to anon;
grant execute on function public.reorder_quick_note_presets(p_organization_id uuid, p_restaurant_id uuid, p_ids uuid[]) to anon;
grant execute on function public.reorder_table_sections(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_ids uuid[]) to anon;
grant execute on function public.restore_device_session(p_device_id uuid, p_session_token text) to anon;
grant execute on function public.revoke_device_management(p_client_request_id uuid, p_device_id uuid, p_reason text) to anon;
grant execute on function public.revoke_device_session(p_device_id uuid, p_session_token text) to anon;
grant execute on function public.revoke_membership(p_client_request_id uuid, p_membership_id uuid, p_reason text) to anon;
grant execute on function public.sales_summary(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid) to anon;
grant execute on function public.set_branch_pos_shift_close_enabled(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_enabled boolean) to anon;
grant execute on function public.set_branch_tax(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_enabled boolean, p_rate_bp integer) to anon;
grant execute on function public.set_employee_pin(p_client_request_id uuid, p_employee_profile_id uuid, p_pin text) to anon;
grant execute on function public.set_printer_route(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_station_id uuid, p_printer_device_id uuid, p_is_enabled boolean) to anon;
grant execute on function public.set_restaurant_receipt_logo(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_logo_path text, p_enabled boolean, p_expected_version integer) to anon;
grant execute on function public.set_table_layout_position(p_client_request_id uuid, p_organization_id uuid, p_table_id uuid, p_layout_x integer, p_layout_y integer) to anon;
grant execute on function public.set_table_section(p_client_request_id uuid, p_organization_id uuid, p_table_id uuid, p_section_id uuid) to anon;
grant execute on function public.set_table_section_floor_preset(p_client_request_id uuid, p_organization_id uuid, p_section_id uuid, p_floor_preset text) to anon;
grant execute on function public.set_table_status(p_client_request_id uuid, p_organization_id uuid, p_table_id uuid, p_status text) to anon;
grant execute on function public.set_table_visual_preset(p_client_request_id uuid, p_organization_id uuid, p_table_id uuid, p_visual_preset text) to anon;
grant execute on function public.soft_delete_printer_device(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid) to anon;
grant execute on function public.soft_delete_quick_note_preset(p_client_request_id uuid, p_organization_id uuid, p_preset_id uuid) to anon;
grant execute on function public.soft_delete_table(p_client_request_id uuid, p_organization_id uuid, p_table_id uuid) to anon;
grant execute on function public.soft_delete_table_section(p_client_request_id uuid, p_organization_id uuid, p_section_id uuid) to anon;
grant execute on function public.start_device_session(p_client_request_id uuid, p_device_pairing_id uuid) to anon;
grant execute on function public.start_pin_session(p_device_session_id uuid, p_employee_profile_id uuid, p_pin_verifier text, p_local_operation_id text) to anon;
grant execute on function public.sync_pull(p_pin_session_id uuid, p_device_id uuid, p_entities text[], p_cursors jsonb, p_limit integer) to anon;
grant execute on function public.sync_push(p_pin_session_id uuid, p_device_id uuid, p_operations jsonb) to anon;
grant execute on function public.update_branch_settings(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_name text, p_address text, p_timezone text, p_receipt_prefix text, p_status text) to anon;
grant execute on function public.update_organization_settings(p_client_request_id uuid, p_organization_id uuid, p_default_currency text, p_country_code text, p_status text) to anon;
grant execute on function public.update_restaurant_settings(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_name text, p_currency_override text, p_timezone text, p_status text) to anon;
grant execute on function public.update_role(p_client_request_id uuid, p_membership_id uuid, p_new_role text) to anon;
grant execute on function public.upsert_floor_element(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_section_id uuid, p_kind text, p_id uuid, p_layout_x integer, p_layout_y integer, p_width_norm integer, p_height_norm integer, p_orientation_quarter_turns integer, p_label text) to anon;
grant execute on function public.upsert_printer_device(p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid, p_display_name text, p_connection_type text, p_role text, p_paper_width text, p_connection_config jsonb, p_is_enabled boolean) to anon;
grant execute on function public.upsert_quick_note_preset(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_id uuid, p_label text, p_is_active boolean) to anon;
grant execute on function public.upsert_table(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid, p_label text, p_seats integer, p_area text, p_is_active boolean) to anon;
grant execute on function public.upsert_table_section(p_client_request_id uuid, p_organization_id uuid, p_restaurant_id uuid, p_branch_id uuid, p_id uuid, p_name text, p_is_active boolean) to anon;
-- 2. Relation privileges that existed for anon (acl letters arwdDxtm = INSERT,SELECT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN): 51 relations
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.app_users to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.audit_events to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.branch_receipt_counters to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.branches to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.cash_drawer_sessions to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.device_pairing_attempt_states to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.device_pairings to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.device_sessions to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.devices to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.employee_profiles to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.item_sizes to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.item_variants to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.management_request_results to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.memberships to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.menu_categories to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.menu_item_branch_availability to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.menu_items to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.modifier_options to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.modifiers to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.order_item_modifiers to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.order_items to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.order_operations to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.order_service_rounds to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.orders to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.organization_subscriptions to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.organizations to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.payments to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.pin_attempt_states to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.pin_sessions to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.plans to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.platform_admin_audit_events to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.platform_admin_grants to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.printer_devices to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.printer_routes to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.quick_note_presets to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.restaurants to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.shift_operations to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.shifts to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.stations to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.sync_operations to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.table_floor_elements to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.table_group_members to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.table_groups to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.table_sections to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.tables to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.daily_branch_sales_report to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.daily_branch_shift_lines to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.daily_branch_void_discount_reasons to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.dashboard_org_daily_sales to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.dashboard_restaurant_daily_sales to anon;
grant insert, select, update, delete, truncate, references, trigger, maintain on table public.organization_entitlements to anon;
-- 3. Default privileges for role postgres in schema public that existed for anon (pg_default_acl rows: r=arwdDxtm, S=rwU, f=X)
alter default privileges for role postgres in schema public grant all on tables to anon;
alter default privileges for role postgres in schema public grant all on sequences to anon;
alter default privileges for role postgres in schema public grant execute on functions to anon;
commit;
